### ISSUE TITLE
ImportError: No module named ptcaccount.exceptions

### ISSUE THREAD

**Issue by Mearman** [jepayne1138/PTCAccount#1]
```
File "accountcreator.py", line 14, in <module>
    from ptcaccount.exceptions import *
ImportError: No module named ptcaccount.exceptions
```

**Comment by jepayne1138** [comment]
Import issues give me a headache.  I didn't have any problems when I tested it in Python 2 or 3...

However, I think I might know what it is and I may have been able to fix the issues.  Seeing as I didn't have any problems myself for some reason in the first place, I'm not sure that I actually took care of the problem.  Could you let me know if the latest version works?

I'm not too practiced with handling releases on Github, so I think because I haven't created a new release you might have to uninstall and reinstall the most recent version.  Should be:

```
$ pip uninstall PTCAccount
$ pip install git+https://github.com/jepayne1138/PTCAccount.git
```

Anyways, let me know if that does the trick.  If not, could you also let me know what version of Python you're running?  Thanks for checking this out!

**Comment by jepayne1138** [comment]
Hmm, that's my bad screwing up the version control.  It looks like it's actually correct in an old version.  I'll take a look and see if I can't straighten it out.

**Comment by jepayne1138** [comment]
So I think this was fixed, and I have release at least two new versions since this was opened, and even changed the imports around, so I think this issue is outdated.  I'm closing the issue, please open another one if you continue to have further problems.
